### PR TITLE
Initial commit for card hover effect

### PR DESCRIPTION
**Pull request by CLobenstein**
Hi Leora
I just commited the card component with the hover effect.
Please let me know which changes I need to make.
Thank you

### CODE REVIEW

**Comment by leowald** [comment]
great - one last issue I see is that for the test when you unhover - you are looking for class card but it always has class card.  I think you need to test and make sure it does not have hover.

**Comment by CLobenstein** [comment]
It doesn't always have class card... Either it has card or cardhover...
depending on state hover...

**Comment by leowald** [comment]
This passes for me:
 await user.hover(card);
    expect(card).toHaveClass(/card/);
    await user.unhover(card);
    expect(card).toHaveClass(/card/);

**Comment by CLobenstein** [comment]
That's because the class hovercard also has the word 'card' in it...
I'll just change it to be an exact match...

**Comment by leowald** [comment]
make sure it works before you push again!

**Comment by CLobenstein** [comment]
No problem!

**Review by leowald — APPROVED** [review]
Great!

**Pull request merged**
