### PR TITLE
initial commit for react-router-layout component

### PR DESCRIPTION
**Pull request by CLobenstein**

### CODE REVIEW

**Review by leowald — CHANGES_REQUESTED** [review]
This looks good.
I didn't yet look at tests for documentation because I see something in the RootLayout.

The task was to:
 The RootLayout component should return the Provider currently wrapped around App. (It would be good to look at the provider and try to understand what it does :). Remove Provider from App. 
You have the AuthProvider but not the Provider that was in App.

Also what are the children doing there?

**Review by leowald — CHANGES_REQUESTED** [review]
Great work.
The rootlayout does not need the divs around it - please remove.
Also when I go to a page say /about - I don't see the H1 coming up that says About.
The same for contact - please fix so that the content comes up on the inner pages. (and then you will also have to fix App.js)
In storybook - the mainlayout component is coming up funny - please fix. 
Also since you added the error page to storybook, can you add the other pages as well?
Thanks.

**Comment by CLobenstein** [comment]
Leora - that's so weird... It comes up by me... e.g. About page, contact
page...

**Comment by leowald** [comment]
It says on it About? Can you send me a screenshot? You can email me.

**Comment by CLobenstein** [comment]
[image: image.png]

**Review by leowald — APPROVED** [review]

**Pull request merged**
