### PR TITLE
initial commit for modal box component

### PR DESCRIPTION
**Pull request by CLobenstein**

### CODE REVIEW

**Review by leowald — CHANGES_REQUESTED** [review]
Great Start!
The size should be passed in by the user and not hardcoded.
There should be no close button at the bottom, should only close by the X

**Comment by CLobenstein** [comment]
I changed the first 2 things.
I'm just not sure about the third - because it works perfectly by me...
Did you check it in storybook? There is an example there...
And also in app.jsx...

**Review by leowald — CHANGES_REQUESTED** [review]
I removed the 3rd problem - so you can ignore.
But there is still an issue, if I want the pop up open by default (which we will want in some cases) and I set it to show={true}, it wont' close.

**Comment by CLobenstein** [comment]
Is that in storybook?

**Comment by leowald** [comment]
I actually didn't check it in storybook but in my own code.
If you run will it close for you?
 <ModalBox
        show={true}
        onHide={() => updateShow(false)}
        modalTitle="Heading for Modal"
        size="md"
      >
        <ModalBody>
          <p>
            Ipsum molestiae natus adipisci modi eligendi? Debitis amet quae unde
            commodi aspernatur enim, consectetur. Cumque deleniti temporibus
            ipsam atque a dolores quisquam quisquam adipisci possimus
            laboriosam. Quibusdam facilis doloribus debitis! Sit quasi quod
            accusamus eos quod. Ab quos consequuntur eaque quo rem! Mollitia
            reiciendis porro quo magni incidunt dolore amet atque facilis ipsum
            deleniti rem!
          </p>
        </ModalBody>
        <ModalFooter>
          
        </ModalFooter>
      </ModalBox>

**Comment by CLobenstein** [comment]
Hi Leora
Did you see what I did in App.jsx?

  const [modalShow, setModalShow] = useState(false);
  const [activeModal, setActiveModal] = useState();

  function handleOpenModal(val) {
    setActiveModal(val);
    setModalShow(true);
  }

  function handleCloseModal() {
    setActiveModal("");
    setModalShow(false);
  }


 <Button
                    variant="primary"
                    onClick={() => handleOpenModal("modal-one")}
                  >
                    Launch first sample modal!
                  </Button>

                  <ModalBox
                    size="lg"
                    show={modalShow && activeModal === "modal-one"}
                    modalTitle="Sample title"
                    onHide={handleCloseModal}
                  >
                    <ModalBody>Sample paragraph to test modal body.</
ModalBody>
                    <ModalFooter>Sample footer</ModalFooter>
                  </ModalBox>

I created 2 states - one to hold true/false and one to hold the name of the
modal that's meant to open...
In order for the modal to 'show', it needs modalShow set to true AND
activeModal set to the right name - to know which modal to open...
That's why if you just set it to true, it won't work as it won't know which
one to open... (I think...)

**Comment by CLobenstein** [comment]
And yes, if I just change it to show={true}, it does open for me...

**Comment by CLobenstein** [comment]
But not close...

**Comment by CLobenstein** [comment]
But it all works if I keep it like I did it before - the code I sent you
just before...

**Comment by CLobenstein** [comment]
If you want it to work, you have to set modalShow = true and activeModal to
have the name of the modal (which the onClick of opening the modal should
also be set to...)

**Comment by CLobenstein** [comment]
Did I do it wrong??

**Comment by leowald** [comment]
> activeModal to have the name of the modal (which the onClick of opening the modal should also be set to...)

Yes but we need it to close as well. We will have cases where it will be open initially on the page and someone will have to come and click the close button.
Also I don't think you changed it to take in the size. The size should not be hardcoded.
Also we don't want animation because we want the box to be on the page initially open.
When you've tested it all and it is all working then push again.

**Comment by CLobenstein** [comment]
Can I ask you another random question?
Every time I start my application again, it makes me re-install
react-bootstrap....
Do you know why?

**Comment by CLobenstein** [comment]
I have it that if I set the state to true and activemodal = "modal-one,
then when the page loads, that modal is open and it can then be closed...
I did do the size - I'm not sure what happened...

**Comment by leowald** [comment]
and can you open and close other pop ups on that page also. What if you want to open another one, when one is open.
I took your code and pasted it into my App.js and used your modal and they way I want it to work, it does not.

**Comment by CLobenstein** [comment]
I'm not sure what I'm supposed to do...
How are 2 supposed to open at the same time?
You mean you want me to take away the overlay that prevents you from
accessing the site when a modal is open?

**Comment by CLobenstein** [comment]
Also, I can create a state constant within the modal so that each modal has
its own state... but then you can't pass in the onHide because it's all
held in the lower level component...

**Review by leowald — CHANGES_REQUESTED** [review]
You are for sure closer than before and probably what you did works but in React we avoid using vanilla javascript like you did. 
Keep working on it, you are doing great and you will only gain :)

**Comment by CLobenstein** [comment]
Could it be that I need to use a different hook like useRef/useReducer?

**Review by leowald — CHANGES_REQUESTED** [review]
You are making progress and learning a lot it seems but
your have the pop up sliding in (when set to true) and I don't want that.
Also if you are going to stick with refs, your code for App.jsx looks too complicated BUT there is a much easier way to do this without ForwardRef. Try a bit more and if you don't figure it out, I will give you a hint :) I think it can work with forwardRef but then you have to pass the Ref in, my way you don't need to pass anything extra in.

**Review by leowald — CHANGES_REQUESTED** [review]
Great. You did it!

- [ ] Please change the updateIsOpen prop name to onHide, because it makes it more clear what it is. The function to be executed onHide.
- [ ] What is this for? onExited={() => updateIsOpen && updateIsOpen("")}
- [ ] Maybe change the name of show2 to something that makes more sense

Please make these changes and I will check also the documentation and tests.

**Comment by CLobenstein** [comment]
I'm still not getting one thing...

I changed the updateIsOpen prop name to onHide and passed it through but we
don't need it at all...
onHide = {() => updateShowModal(false)}
So what does it help to pass in another onHide which updates the isOpen?

**Review by leowald — CHANGES_REQUESTED** [review]
This looks great now.
But:
when you call the function onHide - why are you passing it a string?
Also: I think you need to add more tests: like when you pass in a size does that size show up, when you pass in a title, does that title show up, when you pass in false for show - does it show on the page, what if you pass in true?

Also for storybook - can you create 2: one with the show set to true initially and one set to false. Also if I view the code on storybook for some reason it does not show then show={true} or show={false} it just shows show. See if you can fix that.
Thanks.

**Review by leowald — CHANGES_REQUESTED** [review]
For the test for the title, it does not work because if I change it to:
expect(modal, { name: "Does not work" }).toBeInTheDocument(); it still passes and it should fail as that was not the name.

Also can you do research to see if there is a better way in storybook to pass in children - so that in the control, it can be changed? Let me know what you come up with..

**Review by leowald — CHANGES_REQUESTED** [review]
The test is good now but please spend time looking over how to do children in storybook. You will have to research it and see if there is a better way so that people can put children into storybook and see the results. The way it is, is not so useful.

**Review by leowald — CHANGES_REQUESTED** [review]
I think the way you did the storybook is ok and clear. I'm assuming storybook as a better way of passing in children - but you can leave like this.
I think you just need to say that modalHeader and Footer are optional and that any children can be passed in. Just in text make that clear.
Thanks.

**Review by leowald — APPROVED** [review]

**Pull request merged**
