### PR TITLE
15 documentation

### PR DESCRIPTION
**Pull request by SKupferstein**
Please send feedback

### CODE REVIEW

**Comment by leowald** [comment]
when I try to run storybook - I get this error. Do you see it as well?
Unable to index ./src/docs/env.mdx:
  Error: Expected a closing tag for `<add>` (10:121-10:126) before the end of `paragraph`
    at /app/front/node_modules/@storybook/core/dist/core-server/index.cjs:46238:24
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Es.updateExtracted (/app/front/node_modules/@storybook/core/dist/core-server/index.cjs:46221:5)
    at async Es.ensureExtracted (/app/front/node_modules/@storybook/core/dist/core-server/index.cjs:46258:8)
    at async Es.initialize (/app/front/node_modules/@storybook/core/dist/core-server/index.cjs:46217:5)

**Comment by SKupferstein** [comment]
I think I fixed it. Just wondering - how can you run storybook? i didn't manage to run it at all

**Comment by leowald** [comment]
It it coming up now but the formatting is off. Please do some research to see how to get it either like a table or formatted so it comes out like clear documentation where each item is on a line with its definition. Thanks.

**Comment by SKupferstein** [comment]
Looks good to me now.
I do hope this is what it's expected to be

**Comment by leowald** [comment]
This looks amazing now: Great job.

Please just change the following words:
Change the title to Environment Variables
write a sentence about where this file is located. The .env file is located in the root directory of the project
1.The first one should just be: This variable is used to specify the root password for the MySQL database
2. Second should say: This variable specifies the name of the database that will be used in our application. This is the wordpress database.
3. This variable is the username for the Wordpress MySQL database. 
4. This variable is the password for the Wordpress MySQL database.

**Comment by SKupferstein** [comment]
Edited and pushed to git.

**Comment by leowald** [comment]
look great.

**Pull request merged**
