### PR TITLE
initial commit for css #67

### PR DESCRIPTION
**Pull request by CLobenstein**

### CODE REVIEW

**Review by leowald — CHANGES_REQUESTED** [review]
Is there a reason you left in the App.scss 

// helpers
@import "./sass/helpers/variables";
@import "./sass/helpers/functions";
@import "./sass/helpers/mixins";

**Comment by CLobenstein** [comment]
I think I forgot to take it out... Should I take it out and commit again?

**Comment by CLobenstein** [comment]
Actually, I tested it and you still need it - the variables are used for
other things...

**Comment by CLobenstein** [comment]
for this import - @import "./sass/components/section-title";

**Comment by CLobenstein** [comment]
And other ones...

I'm just leaving it in...

**Review by leowald — APPROVED** [review]
ok I'll leave it for now, I'm assuming later on we will be able to take out as it does not make much sense to me to need it in both.

**Pull request merged**
