### PR TITLE
14 images

### PR DESCRIPTION
**Pull request by SKupferstein**
I wasn't clear about the last part of this issue - replacing the dump.sql file - how did my changes get saved in there?

### CODE REVIEW

**Review by leowald — CHANGES_REQUESTED** [review]
Hi,
Mostly great. Here is what needs to be changed:

- [ ] example.env should not be in front
- [ ] The url in example.env cannot be specific to your computer. It has to work for everyone and be the same url for everyone.
- [ ] Export the wordpress database and save as dump.sql - before you do it remove any posts, categories extra images (expect for the needed ones)

**Comment by SKupferstein** [comment]
example.env in front should be deleted?

**Review by leowald — CHANGES_REQUESTED** [review]
I don't see the example.env file - my issue was that it was in the wrong directory but it needs to be there because the env file is used for images.

**Comment by SKupferstein** [comment]
OK
I'm a little unclear here -
We have one .env file in the main folder, which includes all the
environment variables we have worked with until now, correct?
We have another .env file "example.env" that should include only the
variable carrying the image path. This file shouldn't be in the 'Front'
folder.(where should it be?)

**Comment by leowald** [comment]
we have an example.env in the root not under front

**Comment by SKupferstein** [comment]
So there should be two .env files in the root?

**Comment by leowald** [comment]
Yes but only one gets loaded to github. The regular .env is blocked from getting loaded to github because it has passwords that we don't want shared with everyone.

**Comment by SKupferstein** [comment]
Pushed again - please lmk if it's good now.
Thanks!

**Comment by leowald** [comment]
everything looks good now. I will download and make sure before I push. 
Can you just do the following:

- [ ] change the url from VITE_IMAGE_PATH = http://localhost:8000/wp-content/uploads/ to VITE_IMAGE_PATH : http://localhost:8000/wp-content/uploads/ to be consistent with the rest of the file.
- [ ] Can you give the images more meaningful names like logo, slide ect.
- [ ] If you can use this notation ${ } would be better. What you did works fine, this is just the newer way of doing it.
Thanks. Great job.

**Review by leowald — APPROVED** [review]
All looks great. I am having problems with your database dump. Are you sure it was working wordpress by you? I removed it and will put in my own. Besides for that look excellent.

**Pull request merged**
