### PR TITLE
28 category data

### PR DESCRIPTION
**Pull request by SKupferstein**

### CODE REVIEW

**Review by leowald — CHANGES_REQUESTED** [review]
Looks excellent.
Please just remove all extra things you put in App.js and put it back to the way it was.
In store/categoryContext.jsx you don't need the useContext import - please remove it.
Thanks.

**Comment by SKupferstein** [comment]
It's strange. I removed it from my file before committing for the first time.  Why doesn't it update when pushing?

**Comment by SKupferstein** [comment]
see screenshot
I'm just trying to understand why this would happen - so it shouldn't happen again
Screenshot 2024-12-02 091506

**Comment by leowald** [comment]
Very interesting, I'll check again.

**Comment by SKupferstein** [comment]
If I commit again it tells me "nothing to commit, everything up-to-date"...

**Comment by leowald** [comment]
You can go into the file on github click edit and it will let you edit if
from there. You can commit from there.

**Comment by SKupferstein** [comment]
ok, done.

**Review by leowald — CHANGES_REQUESTED** [review]
Hi,
You still have <test></test> in App.js
Also you seem to be missing the whole component directory. Please see if you can figure out what is going on because you should have everything. You may need to pull the main again and then merge once on your branch from main.

**Review by leowald — CHANGES_REQUESTED** [review]
everything looks great.
Just two more things:

- [ ] When you import files - don't put the filetypes at the end (except for css) so import axiosClient from "../api/axiosClient.js"; should be import axiosClient from "../api/axiosClient
  Please go back and fix that

- [ ] I just forgot to ask you to do something:
Please Add documentation via JSDoc to your Context file - which describes what values are expected and what it is used for / how to use it so other will be able to use it. Thanks.

**Comment by SKupferstein** [comment]
Hi
1. OK
2. I added a documentation mdx file within docs - does that make sense or
it should rather be within the context folder? I'm not sure I'm getting
what type of file you're referring to.

**Comment by leowald** [comment]
No the documentation should be within the jsx file itself using jsdoc (I spoke about it in one of the classes). You can also look at how others did it. storybook will pick up on it from within the file and that way the file is also documented for something reading the code.

**Comment by SKupferstein** [comment]
OK, will do

**Comment by SKupferstein** [comment]
Added - I didn't do this before, and am not sure if this is exactly what
you had in mind.
The jsDoc I put into the jsx file doesn't show up in storybook. I added a
doc.mdx file within the folder and that is what's showing up. Does that
make sense?

**Review by leowald — CHANGES_REQUESTED** [review]
I'm sorry it is my fault why it didn't generate the docs for you.
Under storybook in main.js add your folder path to here: folderPaths: ["./src/hooks", "./src/utils"], // paths to folders with JS/TS code
Now remove your mdx file you wrote and only have the code in your provider. It should generate the mdx for you. 
Also now you have a lot of extra files that were pushed, please delete them - so they don't get merged.

**Comment by SKupferstein** [comment]
Thanks
I did it but it's still not showing up. I see that whoever worked on the
file 'styles' within 'utils' had the same problem - she had jsdoc within
her file and also an mdx file, and only the mdx shows in storybook...

**Comment by leowald** [comment]
The jsdoc should automatically create the mdx file when it is run in docker. Are you sure it is not? If you added the path correctly , it should auto-generate it. LMK.

**Comment by SKupferstein** [comment]
Unfortunately it's still not working for me.
I tried removing the mdx file from utils to see if that file would generate
mdx but it's also not getting created when running docker...

**Review by leowald — CHANGES_REQUESTED** [review]
I still see way too many files in this push. Once you have removed what does not need to be on it, I will check why the comments are not working.

**Comment by leowald** [comment]
Also I played around with it and did get the mdx file to generate automatically. Maybe I won't tell you how, I did have to figure out why in one place it worked and the other not and then work things through - I've leave it for you to do, good learning experience!

**Comment by SKupferstein** [comment]
I pushed it now. (removed the files, sorry about that)
For me it's not generating mdx in either place. I would appreciate it if
you could test it by yourself and see if it's working for you. It might be
connected to a different issue I'm having with storybook, which I'm
spending days trying to fix but am not managing...

**Comment by SKupferstein** [comment]
This is what I did - I deleted the mdx from the file styles.jsx within
utils (a file that I didn't work on), and it didn't get generated either.

**Comment by leowald** [comment]
check that your storybook main.js has this in it. If it does, I'll check
and see if yours is working

 folderPaths: ["./src/hooks", "./src/utils", "./src/providers"], // paths
to folders with JS/TS code

**Comment by SKupferstein** [comment]
The instruction was to add the jsdoc to categorycontext which is within
'store', so my .storybook > main.js has this:
        folderPaths: ["./src/hooks", "./src/utils", "./src/store"], //
paths to folders with JS/TS code

        extensions: ["ts", "js", "jsx", "mjs"], // file extensions to
include

**Comment by leowald** [comment]
ok but utils is there, so it should work if you remove it. So maybe first
get storybook working before you try to solve this problem.
You will need storybook for the future and I am not in a rush for this - so
get tha working first.

**Comment by SKupferstein** [comment]
Storybook crashes everytime after opening it because of some error
connected to fontawesome. I spent the last few days trying to figure it out
but nothing worked so far,,...

**Comment by leowald** [comment]
I would download the current project on github to a different directory and
run it in docker and see if you have the same issue.

**Comment by SKupferstein** [comment]
Thanks. I actually tried that already, but I'm still getting the same
error! (Are you not getting any error with storybook??)

**Comment by leowald** [comment]
Ok so reach out to someone on the team and maybe even do a zoom call to see
how theirs works - then you will know if there is a general issue or a
specific issue to yours.

**Review by leowald — CHANGES_REQUESTED** [review]
Hi,

- [ ] Please spend time trying to figure out why your .env file is being pushed to github. If you were in a real company and this was happening, it would be very bad. It should be in your .gitignore and should not.
- [ ] It seems like you added some lines to preview.js - something with fontawesome - please remove them.
- [ ] Also your sample.env seems to be missing things that we need and if I push it, those things will be lost.

**Comment by SKupferstein** [comment]
OK, working on it.
I just pushed to git - please ignore it.
Thanks

**Comment by SKupferstein** [comment]
Mylast commit "changes done" should be alright.
Please let me know.
Thank you!

**Review by leowald — APPROVED** [review]
excellent

**Pull request merged**
