### PR TITLE
19 card component

### PR DESCRIPTION
**Pull request by CLobenstein**
Hi Leora
I changed a few things and added a unit test for the card component.

### CODE REVIEW

**Review by leowald — CHANGES_REQUESTED** [review]
Hi,

Overall excellent.
Please fix the following:

- [ ] it does not look like your work is saved with prettier. please make sure that it does - you should enable it on save so that it does.
- [ ] The css from for the card should be taken from the original template (the parts that are relevant. Your numbers are different, the shadow is missing and I don't see for different screen sizes, which is in the original template.
- [ ] You need to use css modules, which you are not.
- [ ] The getbackground documentation needs to be in the file itself not under docs. I see why you had trouble with it. Go to storybook/main.js and add in your folder path.
- [ ] For getbackground - if a person does not pass in a background don't set it to 180 it just does not have the background like: background: linear-gradient(#e66465, #9198e5);
- [ ] instead of  if(background.sideCorner == null) {
            background.sideCorner = ""; 
        }
see if you can write this is one line. Again this is just code enhancement what you did is correct.

- [ ] when you loop through the colors, you may want to use another function on the array which will help you tighten up (make the code) shorter. Although again what you did works!
- [ ] Is there a place in storybook that you can write out what the object should look like? What is required and what is optional? You should add it to make it clear for something wanting to use it.
- [ ] Also be sure to test it with your docs and put in all types found in https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient (the 3 top examples)
- [ ] for your tests. Please remove screen.debug also your test of color: backgroundexample does not work because you are checking that the background color is an object - not the linear graidant.

**Comment by leowald** [comment]
I have not had a chance to go through it all yet. So far this is what I see:

- [ ] css modules have not been added
- [ ] your scss file looks good but it looks like there is extra in it.  Please go through each item and remove what is not necessary.
- [ ] When testing in storybook - it seems that passing something like this does not work: please check all possible combinations either through storybook or create your own manual tests.
{
  "colors": [
    {
      "color": "red"
    },
    {
      "color": " green",
      "deg": "50%"
    }
   
  ]

Please fix the above and then I will review again.
Thanks.

**Comment by leowald** [comment]
- [ ] You have a typo in storybook/main.js which is causing problems loading storybook
- [ ] Under utils remove the storybook files you created, they are also causing issues and not right. 
- [ ] Please go back to the class on storybook which shows how to write comments within the styles.jsx file. We want our comments there, not in a separate file
- [ ] Your scss looks much better but is now missing padding
- [ ] When I start storybook, I don't see the cards anymore.
- [ ] Please move your tests to a folder under tests/components

Other than that all code looks great!

**Comment by CLobenstein** [comment]
It's so funny because I have no issues with storybook...
What files are you referring to???
How does it make sense that you don't see the cards??

**Review by leowald — APPROVED** [review]
looks great.

**Pull request merged**
