### PR TITLE
initial commit for 23-icon-component

### PR DESCRIPTION
**Pull request by CLobenstein**

### CODE REVIEW

**Review by leowald — CHANGES_REQUESTED** [review]
The code looks excellent but I can't test because when I run in docker I am getting the following errors:
 Error: The following dependencies are imported but could not be resolved:
storybook       | 
storybook       |   @fortawesome/react-fontawesome (imported by /app/front/src/components/Icon.jsx)
storybook       |   @fortawesome/fontawesome-svg-core (imported by /app/front/src/components/Icon.jsx)
storybook       |   @fortawesome/free-solid-svg-icons (imported by /app/front/src/components/Icon.jsx)
storybook       |   @fortawesome/free-regular-svg-icons (imported by /app/front/src/components/Icon.jsx)
storybook       |   @fortawesome/free-brands-svg-icons (imported by /app/front/src/components/Icon.jsx)

**Comment by CLobenstein** [comment]
I didn't run it in docker because it doesn't work with the filter...

**Review by leowald — CHANGES_REQUESTED** [review]
I can now run storybook in docker.
I know this is not your issue but the error component is coming up not under components like the rest, can you change?

Also I think this part is missing: **If the bottom icon is passed in via props (ie a color property )is passed but not a name the default name should be set as fa-circle, if a color is passed but not a type, the default should be fas** 
If a bottom icon is not passed - there should be no bottom icon but in storybook an empty bottom icon is coming up with a circle? Maybe you just have to change something in storybook or it is a bug in your code?

Also for the error component, I think I would make the logo smaller and maybe remove the circle?

**Comment by CLobenstein** [comment]
I'll try change it...

I did do it - here is that part of the code:
            icon={`${bottomIcon.name ? bottomIcon.name : "fa-circle"} ${
              bottomIcon.type ? bottomIcon.type : "fas"
            }`}

**Comment by CLobenstein** [comment]
Oh and btw that circle is just testing from the style of the top
component... It's nothing to do with the bottom component...

**Comment by CLobenstein** [comment]
And I sorted out the Error component - can I commit it from my 23-icon
branch?

**Comment by leowald** [comment]
yes.
Maybe just put one in storybook that only has one icon.

**Review by leowald — CHANGES_REQUESTED** [review]
sorry I'm being picky but I want to make sure that to everyone using it that it is clear.

- [ ] For the Error Component, I think the icon is too big. Please take out the circle and just have the triangle and match its color to the Error Text color. Maybe try size 3
- [ ] For Icon.jsx can you make the size that they don't need to pass in the x - it will make it more user friendly. 
- [ ] For Icon.jsx the way you programmed it is great - but just to show you how to upgrade your code. You could write: 
bottomIcon.type ? bottomIcon.type : "fas"
as bottomIcon.type || "fas" 

- [ ] For storybook - I just want it to be clear to others:
First of all there is a typo: font-awesome incon accordingly
Then color,name,type, style(optional) and extras(optional). These needs to be explained more so people know what they are and what to put in.
For the size option in storybook - please make it a dropdown with only the possible values..

Thanks.

**Review by leowald — APPROVED** [review]
looks great!

**Pull request merged**
