### PR TITLE
17 faker

### PR DESCRIPTION
**Pull request by SKupferstein**
I followed all the instructions in issue 17. One thing I see is that although the new command is working well - when running docker it creates a file db.json and pulls in the data from data.mjs, when I open localhost:3000 it doesn't work. I'll appreciate it if you could help me find the issue.

Also, I wanted to create a docker file for faker, so that we won't need all the node-moduels in the program. It wasn't included in the task, though, so I wanted to ask you if it makes sense to create one, and if yes, if you could give me some guidelines on how to create.

Thank you!

### CODE REVIEW

**Comment by leowald** [comment]
Hi,
First of all this task is hard and requires a lot of time, so don't try to expect that it will go fast.
We are adding to docker - that is what this doe: **Add to the docker-compose.yml file a service called faker. Put in the correct build, add the command: npm run filldata and the key to get this working within docker is to add in the correct volume so that it is bound to the correct place that the json server reads in. Make the json_server dependant on faker. Make sure it is all running correctly.**
Even if you don't add to docker you should not upload nodemodules. it should be in gitignore. 
Lastly, if I help you figure out the problem, you will lose out on the learning experience. Take the time and work through it. I have confidence in you!

**Comment by leowald** [comment]
Hi,
It looks to me that when you run docker docker compose up --build , that the json file under data does not get recreated. This is actually the tricky part of this task. Remove your file or empty it and see if it does get created. If it does not, like I think - read the hint again.

**Comment by SKupferstein** [comment]
I might not have understood the task correctly - was I supposed to recreate
the db.json file within data - and override the posts, comments etc. from
the file with the categories and stories created through faker? or create a
new json file?
from the task I read:
Run: npm run filldata and see that the db.json file gets created (does not
matter where it gets created at this point, just that it gets created.
This seems to be working for me - a json file is created with the src
folder when running docker

**Comment by leowald** [comment]
Yes, json server only works with a certain file. The last task within the task is to use docker to get it writing to that file.
So yes, override the posts, comments ect. In that way we will be able to use it in the project.

**Comment by SKupferstein** [comment]
Now I get it, this makes sense!
Working on it...

**Comment by SKupferstein** [comment]
I know you don't want me to ask any questions, but I will still voice this
one:
The build I put in for faker in docker-compose.yaml is ./front - which I
think is correct.
But - when I try to create the db.json file with data, it won't let me,
tells me 'Directory nonexistent' - while the directory clearly exists, and
calling 'npm run filldata' works while I'm in workdir 'front' .
I looked it up and found the following:'The <src> path *must be inside the
context of the build*; because the first step of a docker build is to send
the context directory (and subdirectories) to the docker daemon.'

Does it make sense that the data folder should be moved to be within front?
or is there a different way to make it work?

**Comment by leowald** [comment]
The build is correct. Keep working on it. It took me a while until I solved it but I did point you in the right direction. If it takes time that is ok.. this is hard but I thought you were up for the challenge.

**Comment by SKupferstein** [comment]
OK
As long as I know that there's an existing way to do it...

**Comment by SKupferstein** [comment]
Thanks
It worked BH, pushed to git.
I see that I always have the same issue - I get it write but with small
detail wrong, and when it doesn't work I figure that I was wrong, spend
hours or days looking it up and trying different things, until I finally go
back to the first option I did on my own with that small difference, and
all is working...:) I'm surely learning a LOT from this experience.

I'm just wondering about this - every time someone will run docker build,
it will re-create the json files, is it not better to create once and work
with that?

**Review by leowald — APPROVED** [review]
looks great

**Pull request merged**
